name: "gh-action-pip-audit"
author: "William Woodruff <william@trailofbits.com>"
description: "Use pip-audit to scan Python dependencies for known vulnerabilities"
inputs:
  summary:
    description: "render a Markdown summary of the audit (default true)"
    required: false
    default: true
  no-deps:
    description: "don't do any dependency resolution (requires fully pinned requirements) (default false)"
    required: false
    default: false
  require-hashes:
    description: "enforce hashes (requirements-style inputs only) (default false)"
    required: false
    default: false
  vulnerability-service:
    description: "the vulnerability service to use (PyPI or OSV, defaults to PyPI)"
    required: false
    default: "PyPI"
  inputs:
    description: "the inputs to audit, space separated (defaults to current path)"
    required: false
    default: ""
  internal-be-careful-allow-failure:
    description: "don't fail the job if the audit fails (default false)"
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - run: python -m pip install --requirement requirements.txt
      shell: bash
    - run: ${{ github.action_path }}/action.py "${{ inputs.inputs }}"
      env:
        GHA_PIP_AUDIT_SUMMARY: "${{ inputs.summary }}"
        GHA_PIP_AUDIT_NO_DEPS: "${{ inputs.no-deps }}"
        GHA_PIP_AUDIT_REQUIRE_HASHES: "${{ inputs.require-hashes }}"
        GHA_PIP_AUDIT_VULNERABILITY_SERVICE: "${{ inputs.vulnerability-service }}"
        GHA_PIP_AUDIT_INTERNAL_BE_CAREFUL_ALLOW_FAILURE: "${{ inputs.internal-be-careful-allow-failure }}"
      shell: bash
